# default config possible values are Server, Build, LocalDev
node.default['BiztalkCookbook']['DefaultConfig'] = 'Server'

node.default['BiztalkCookbook']['BTS_InstallDirectory']='c:\\setup\\bts'
node.default['BiztalkCookbook']['BTS_ISOFile']='c:\\setup\\bts\\BTS.Iso'
node.default['BiztalkCookbook']['BTS_FeaturesFile']='c:\\setup\\bts\\BizTalkFeatures.xml'
node.default['BiztalkCookbook']['VS_ISOFile']='c:\\setup\\vs\\en_visual_studio_ultimate_2013_with_update_5_x86_dvd_6815896.iso'
node.default['BiztalkCookbook']['VSAdminDeploymentFile']='c:\\setup\\vs\\AdminDeployment.xml'
node.default['BiztalkCookbook']['BTS_DependencyCab']='c:\\setup\\bts\\BTSRedistW2k8EN64.cab'
node.default['BiztalkCookbook']['BTS_DependencyCabUrl'] = 'https://server.com/BtsRedistW2K12EN64.cab'
node.default['BiztalkCookbook']['BTS_LogFile']='c:\\setup\\bts\\Install.log'
node.default['BiztalkCookbook']['BTS_ISOUrl'] = 'https://server.com/en_biztalk_server_2013_r2_developer_edition_x86_and_x64_dvd_4445857.iso'
node.default['BiztalkCookbook']['BTS_FeaturesFileUrl'] = 'https://server.com/BizTalkConfig.xml'
node.default['BiztalkCookbook']['BTS_DeploymentFrameworkMsiUrl'] = 'https://server.com/DeploymentFrameworkForBizTalkV5_6.msi'
node.default['BiztalkCookbook']['VS2013_IsoUrl'] = 'https://server.com/en_visual_studio_ultimate_2013_with_update_5_x86_dvd_6815896.iso'
node.default['BiztalkCookbook']['SQLXmlUrl'] = 'https://server.com/sqlxml_x64.msi'
node.default['BiztalkCookbook']['BTS_BuildFeaturesFile'] = 'c:\\setup\\bts\\BizTalkBuildFeatures.xml'
node.default['BiztalkCookbook']['BTS_LocalDevFeaturesFile'] = 'c:\\setup\\bts\\BizTalkLocalDevFeatures.xml'
node.default['BiztalkCookbook']['SQL_ISOUrl'] = 'https://readonly:1234@abc.com/software/microsoft/sql_server/2014/en_sql_server_2014_developer_edition_with_service_pack_2_x64_dvd_8967821.iso'
node.default['BiztalkCookbook']['BTS_SvcHostAccount'] = 'SvcBizTalkHost'
node.default['BiztalkCookbook']['BTS_SvcHostAccountDomain'] = 'ADDOMAIN'
node.default['BiztalkCookbook']['BTS_SvcHostAccountPassword'] = '123Welcome!@#'
node.default['BiztalkCookbook']['BTS_SvcIsoHostAccount'] = 'SvcBizTalkIsoHost'
node.default['BiztalkCookbook']['BTS_SvcIsoHostAccountDomain'] = 'ADDOMAIN'
node.default['BiztalkCookbook']['BTS_SvcIsoHostAccountPassword'] = '123Welcome!@#'
node.default['BiztalkCookbook']['SQL_ServerName'] = '.'
node.default['BiztalkCookbook']['SQL_LocalServerName'] = '.'
node.default['BiztalkCookbook']['SQL_ISO_FILE'] = 'c:\\setup\\sql\\en_sql_server_2014_developer_edition_with_service_pack_2_x64_dvd_8967821.Iso'
node.default['BiztalkCookbook']['BTS_LocalSvcHostAccount'] = 'svcBizTalkHost'
node.default['BiztalkCookbook']['BTS_LocalSvcHostAccountDomain'] = '.'
node.default['BiztalkCookbook']['BTS_LocalSvcHostAccountPassword'] = '123Welcome!@#'
node.default['BiztalkCookbook']['BTS_LocalSvcIsoHostAccount'] = 'svcBizTalkIsoHost'
node.default['BiztalkCookbook']['BTS_LocalSvcIsoHostAccountDomain'] = '.'
node.default['BiztalkCookbook']['BTS_LocalSvcIsoHostAccountPassword'] = '123Welcome!@#'
node.default['BiztalkCookbook']['ESB_Itinerary_DBName'] = 'EsbItineraryDb2013_AWS1'
node.default['BiztalkCookbook']['ESB_Exception_DBName'] = 'EsbExceptionDb2013_AWS1'
node.default['BiztalkCookbook']['VS_InstallLog'] = 'c:\\setup\\vs\\install.log'
node.default['BiztalkCookbook']['VS_InstallPath'] = 'd:\\Program Files'
node.default['BiztalkCookbook']['SQL_DynamicInstanceName'] ='https://readonly:1234@ServerNameService/computerName.txt'

#Amazon Information - Must fill in with your correct information
node.default['BiztalkCookbook']['aws_s3_bucket'] = 's3bucketname'
node.default['BiztalkCookbook']['aws_access_key_id'] = 'keyid'
node.default['BiztalkCookbook']['aws_secret_access_key'] = 'secret'
node.default['BiztalkCookbook']['aws_owner'] = 'owner'
